### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-go#2]
# Description

This issue describes the set of tasks to complete in order to finish up work on the library.

# Tasks

- [x] Touch base with the @jobarratt and @pwalsh to notify that you consider the work complete
- [x] Provide a short description / link to code for how each action is implemented, with a link to unit tests that prove each action
- [x] Tag your candidate code as v0.1
- [x] Setup travis to auto deploy tagged versions to the package management solution for your language
- [x] Ensure that the OKI account on the package management platform is an administrator/maintainer of the package, along with yourself
- [x] Receive code review from @pwalsh and address any remaining issues
- [ ] Publish final version

**Comment by danielfireman** [comment]
@pwalsh @jobarratt I believe we have a tableschema-go implementation :smile:

**Comment by danielfireman** [comment]
I am going to add Documentation and Contribution sections to Readme, following tableschema-js. I believe that would be better than links to code for each action (second checkbox of the list above), right?

cc/ @roll

**Comment by roll** [comment]
@danielfireman 
Yes. It will be better. And following `tableschema-js` readme structure will be great.

**Comment by danielfireman** [comment]
Cool.

AlreadtyAlready added the added the [examples](https://github.com/frictionlessdata/tableschema-go/tree/master/examples). 

Going to ping this thread when the readme section is done (ETA: Thursday)

**Comment by danielfireman** [comment]
Improved the readme quite a lot. Could you please start taking a look, @roll

**Comment by roll** [comment]
@danielfireman 
Thanks. I'll do in coming days.

**Comment by roll** [comment]
@pwalsh 
@danielfireman 
I've reviewed based on http://specs.frictionlessdata.io/implementation/ and found only two basically small things to address:
- support for remote schema descriptors - #35 
- support for "any" type - #36

Not functional thoughts:
- it's hard for me to have an opinion on the API. It seems a Java implementation looks more familiar for me - https://github.com/frictionlessdata/tableschema-java. I mean naming(?), overall workflow. For people it will be easier to adopt Python/JavaScript tutorials etc for Java one. But as we've discussed earlier in design issue it seems a GO limitation to have an API like this. It's the most low-level language we use. So can't judge here.
- my experience of doing this review that README still need some amount of work. For now I think it does not cover the whole functionality while GoDoc reference is still a reference - not really helping to understand how to work with the library.

**Comment by danielfireman** [comment]
Thanks a lot, @roll for the thorough review! Super nice to have an experienced pair of eyes on this project!

Already added support for "any" type and also added the remote load of both schema descriptors and tables.

I am going to enrich the README, but I don't think it should cover the whole package usage and GoDocs plays a larger role here as GoDocs is more than mere references. It supports *examples*, which are executed as tests, thus forcing us to update them as we update the library. For instance, please take a look at the [schema package godoc](https://godoc.org/github.com/frictionlessdata/tableschema-go/schema). While reading GoDocs, I usually scroll a bit down to check the examples section. Currently, this section lists 5 examples:

[InferImplicitCasting](https://godoc.org/github.com/frictionlessdata/tableschema-go/schema#example-InferImplicitCasting)
[Schema.Decode](https://godoc.org/github.com/frictionlessdata/tableschema-go/schema#example-Schema-Decode)
[Schema.DecodeTable](https://godoc.org/github.com/frictionlessdata/tableschema-go/schema#example-Schema-DecodeTable)
[Schema.Encode](https://godoc.org/github.com/frictionlessdata/tableschema-go/schema#example-Schema-Encode)
[Schema.EncodeTable](https://godoc.org/github.com/frictionlessdata/tableschema-go/schema#example-Schema-EncodeTable)

Furthermore, the example also shows up at the method documentation. For instance, the [Schema.Decode method](https://github.com/frictionlessdata/tableschema-go/blob/master/schema/schema.go#L174)

**Comment by danielfireman** [comment]
Improved the `README.md` quite a lot. I believe it is now covering the main aspects of the project and providing plenty of examples. Thanks again for your review, @roll !

**Comment by danielfireman** [comment]
Finished the constraints part. @roll could you please take a look?

**Comment by roll** [comment]
@danielfireman 
Changes looks good. 

The implementation looks completed now and I have only one concern - naming. Unlike all other implementation it seems this one use very different language (method naming etc). So it could be very hard for user to adopt our Python/JavaScript tutorial (which we will be having a lot) to the Go implementation. Good amount of discrepancies of course are related to low-level static typed nature of Go. But I'm wondering is there is a space for improvements? E.g. everyone in FD-world knows that we do `field.cast` (and in general a `cast` word is part of our vocabulary consistently) so is there a good reason to have `field.decode` instead in Go?

**Comment by danielfireman** [comment]
@roll The main reason to use Encode and Decode is to keep consistency to the widely used  [encoding/json](https://golang.org/pkg/encoding/json/) package. In the same way, other libraries that deal with CSV, i.e. [gocsv](https://github.com/gocarina/gocsv), also follow the JSON standard library and use Marshal and Unmarshal.

This is confirmed by some github searches:
* the word cast in golang code: [42K](https://github.com/search?utf8=%E2%9C%93&q=Cast+language%3AGo&type=Code)
* the word Encode in golang code: [464K](https://github.com/search?utf8=%E2%9C%93&q=encode+language%3AGo&type=Code)
* the word Decode in golang code: [555K](https://github.com/search?utf8=%E2%9C%93&q=encode+language%3AGo&type=Code)

That said, @roll @pwalsh  are we trying to make programming easier for folks who come from other libs or for folks who are acquainted with go?

**Comment by roll** [comment]
@danielfireman 
For now the strategy for all implementations:
- use target language best practices and idioms
- but still be as much as possible closer to Frictionless Data naming conventions - https://github.com/frictionlessdata/implementations#tableschema
The second one is because there is a very good chance that people will be coming to target language implementations from Python/JavaScript tutorials, how tos etc

**Comment by danielfireman** [comment]
Renaming is done.

The infer example looks like:

```go
	tab, err := csv.NewTable(csv.FromFile("data_infer_utf8.csv"), csv.SetHeaders("ID", "Age", "Name"))
	if err != nil {
		panic(err)
	}
	fmt.Println("## Raw Table ##")
	fmt.Println(tab)
	sch, err := schema.Infer(tab)
	if err != nil {
		panic(err)
	}
	fmt.Println("## Schema ##")
	fmt.Println(sch)
	var users []user
	sch.CastTable(tab, &users)
	fmt.Printf("\n## Cast Table ##\n%+v\n", users)
```

**Comment by danielfireman** [comment]
v1.0 Released: https://github.com/frictionlessdata/tableschema-go/releases
